const questions = [
  {
    question:
      "In your opinion, how well known is your brand/business within your target market?",
    answer1: "Great!",
    answer1Total: "4",
    answer2: "Good",
    answer2Total: "3",
    answer3: "Could be better",
    answer3Total: "2",
    answer4: "We are not well known...",
    answer4Total: "1",
  },
  {
    question: `Of those who know about your brand/business, how many know what makes you unique from your competitors?`,
    answer1: "Pretty much everyone",
    answer1Total: "4",
    answer2: "Most",
    answer2Total: "3",
    answer3: "Few",
    answer3Total: "2",
    answer4: "Probably none",
    answer4Total: "1",
  },
  {
    question:
      "How effective are you currently in educating potential customers about your product or service?",
    answer1: "Very effective",
    answer1Total: "40",
    answer2: "Important but ineffective",
    answer2Total: "30",
    answer3: "Not very important and ineffective",
    answer3Total: "20",
    answer4: "Unimportant and non-existent",
    answer4Total: "10",
  },
  {
    question:
      "How important and effective is social media to your marketing and sales goals (e.g. leads, awareness, engagement)?",
    answer1: "Important and effective",
    answer1Total: "40",
    answer2: "Important but ineffective",
    answer2Total: "30",
    answer3: "Not very important and ineffective",
    answer3Total: "20",
    answer4: "Unimportant and non-existent",
    answer4Total: "10",
  },
  {
    question: "In your opinion, how easy is it for someone to become a customer?",
    answer1: "We make it very easy",
    answer1Total: "400",
    answer2: "It's standard to our industry",
    answer2Total: "300",
    answer3: "The process could be made easier",
    answer3Total: "200",
    answer4: "It requires more work and handholding than it should",
    answer4Total: "100",
  },
  {
    question:
      "How effective is your sales process to take interested enquires through to customer or client?",
    answer1: "Very effective",
    answer1Total: "400",
    answer2: "Mostly effective",
    answer2Total: "300",
    answer3: "Could be better",
    answer3Total: "200",
    answer4: "Not very effective at all",
    answer4Total: "100",
  },
  {
    question:
      "How likely is it that your past clients purchase from you again, or become recurring clients?",
    answer1: "All the time",
    answer1Total: "4000",
    answer2: "Sometimes",
    answer2Total: "3000",
    answer3: "Rarely",
    answer3Total: "2000",
    answer4: "Never",
    answer4Total: "1000",
  },
  {
    question:
      "How likely are you to retain a client, even if a direct competitor lowers their prices to be slightly less than yours?",
    answer1: "Likely",
    answer1Total: "4000",
    answer2: "Usually",
    answer2Total: "3000",
    answer3: "Not typical",
    answer3Total: "2000",
    answer4: "Unlikely",
    answer4Total: "1000",
  },
];
