const questions = [
  {
    question:
      "How would you rate the current level of awareness of your brand/business with your target market?",
    answer1: "Very high",
    answer1Total: "4",
    answer2: "Good",
    answer2Total: "3",
    answer3: "Poor",
    answer3Total: "2",
    answer4: "Very low",
    answer4Total: "1",
  },
  {
    question: `Of those that are aware of your brand/business, how many do you feel understand the "what" and "how" of your brand/business?`,
    answer1: "Pretty much everyone",
    answer1Total: "4",
    answer2: "Most",
    answer2Total: "3",
    answer3: "Very few",
    answer3Total: "2",
    answer4: "Probably none",
    answer4Total: "1",
  },
  {
    question:
      "How often do you aim to educate or inform your audience in your area of expertise or niche knowledge?",
    answer1: "All the time",
    answer1Total: "40",
    answer2: "Sometimes",
    answer2Total: "30",
    answer3: "Every once in a while",
    answer3Total: "20",
    answer4: "Rarely",
    answer4Total: "10",
  },
  {
    question:
      "If you were to publish a video, image or post on your business social media page, what's the likelihood that this content would be shared, commented on or 'liked' by your audience?",
    answer1: "We always get engagements on our posts",
    answer1Total: "40",
    answer2: "Depends on what kind of post",
    answer2Total: "30",
    answer3: "It's rare",
    answer3Total: "20",
    answer4: "We feel like we publish content that no one sees",
    answer4Total: "10",
  },
  {
    question: "How easy is it for a customer to purchase your product?",
    answer1: "It's a frictionless experience",
    answer1Total: "400",
    answer2: "It's easy enough",
    answer2Total: "300",
    answer3: "It's not very easy",
    answer3Total: "200",
    answer4: "This is a hard thing to buy, with a long sales process",
    answer4Total: "100",
  },
  {
    question:
      "How effective is your sales process to take interested enquires through to customer or client?",
    answer1: "Very effective",
    answer1Total: "400",
    answer2: "Mostly effective",
    answer2Total: "300",
    answer3: "Could be better",
    answer3Total: "200",
    answer4: "Not very effective at all",
    answer4Total: "100",
  },
  {
    question:
      "How likely is it that your past clients purchase from you again, or become recurring clients?",
    answer1: "All the time",
    answer1Total: "4000",
    answer2: "Sometimes",
    answer2Total: "3000",
    answer3: "Rarely",
    answer3Total: "2000",
    answer4: "Never",
    answer4Total: "1000",
  },
  {
    question:
      "How likely are you to retain a client, even if a direct competitor lowers their prices to be slightly less than yours?",
    answer1: "Likely",
    answer1Total: "4000",
    answer2: "Usually",
    answer2Total: "3000",
    answer3: "Not typical",
    answer3Total: "2000",
    answer4: "Unlikely",
    answer4Total: "1000",
  },
];
